openstack:
    keystone:
        url: https://os2-nfvlab.argela.com.tr:5000/v3
        system_user:
            name: argela_admin
            password: argela
            domain: default
            project: argela_admin
            
testData:
    system_user:
        name: argela_admin
        password: argela
        domain: default
        project: argela_admin
    
    identity_service:
        domain:
            name: nebi-domain10
            project:
                name: nebi-project10
            users:
                test1:
                    name: nebi_user_10
                    password: argela
    compute_service:
        domain:
            name: argela
            project:
                name: main-project
        flavor:
            name: nebi-test1
            vcpus: 2
            ram: 4096
            disk: 20
            